### ISSUE TITLE
Motherboard Fan not running

### ISSUE THREAD

**Issue by d4rk50ul1** [Dviros/Klipper-Configs#1]
Hi Just writting this as a bug to see if perhaps you could guide me through. I have a Genius pro as well and did the klipper mod and followed pretty much all of your configs. Now what happens to me is that the fan that the board has never kicks on. not sure if it is because it is not recognized or what. Do you have any experience with this?

**Comment by Dviros** [comment]
Hey! I'll need more info regarding the board you're using and to which PIN did you connect it to.
My config allows to set a temperature goal that will make the fan active in order to achieve it; I can provide more info once I'll know which board is used.

**Comment by d4rk50ul1** [comment]
i'm using the regular artillery genius pro and i believe it is the ruby 32 bits. not sure how should i set the printer.cfg so that it kicks the mainboard fan whenever certain temperature raises. i touch the metal frame from time to time and feels warm. i created the motherboard sensor and it has never gone up from 35 celsius, however, i want to keep my machine safe and sound as much time as possible!

**Comment by Dviros** [comment]
Sure,
You should try the following piece of code:
https://github.com/Dviros/Klipper-Configs/blob/1b6874285671a6e29228000aff8c54965a6464a5/hardware/fans.cfg#L10

Make sure to mention the correct pin for the Ruby fan :)
Good luck
