### ISSUE TITLE
adxl.cfg not found

### ISSUE THREAD

**Issue by mattexx04** [Dviros/Klipper-Configs#2]
hi, the file adxl.cfg is missing.

**Comment by Dviros** [comment]
No need for the adxl file as it was implemented in the printer.cfg:
https://github.com/Dviros/Klipper-Configs/blob/1b6874285671a6e29228000aff8c54965a6464a5/hardware/printer.cfg#L60C1-L60C1

How do you plan to connect it? What sort of adxl sensor are you using?

**Comment by mattexx04** [comment]
sono nuovo nel mondo di klipper nno so cosa sia il sensore adxl e poi volevo sapere avendo una genius pro stock devo usare solo i file di macros e genius pro stock printer.cfg giusto?

**Comment by mattexx04** [comment]
i am so stupid sorry... i am new in the world of klipper and i don' t know what adxl is and i also want to know if having a stock genius pro i have to use only the file geniuspro printer.cfg and macros.cfg or i need other files
